language: python
python:
- '3.6'
install:
- make build
- export ARTIFACT_NAME=`make get-artifact-name`
script:
- make test

deploy:
    provider: releases
    skip_cleanup: true
    api_key: "$GITHUB_OAUTH_TOKEN"
    file:
      - "$ARTIFACT_NAME"
    draft: true
    on:
      branch: master
