@startuml
folder parcel_router{
  [parcel router]-->[parcel grabber]
  [parcel grabber]-->[dsdax]
}

[package builder]->[parcel router]
[dsdax]-->[parcel export controller]
[dsdax]-->[parcel export controller1]
@enduml
