@startuml

class "Component" as component{
    name
    type: [application,product]
}

class "Component Relation" as componentrelation{
    start
    end
    relationType: [contains,calls]
}

class DatamodelRelation{
    start
    end
    relationType: [contains,fk, uses]
}

class DatamodelObject{
    name
    type: [database_user, table, column]
}


DatamodelObject::name <-- DatamodelRelation:start/end
component::name <-- componentrelation:start/end

@enduml